### ISSUE TITLE
Comments on `README.md` and the Python specification

### ISSUE THREAD

**Issue by siv2r** [BlockstreamResearch/bip-frost-dkg#61]
Great specification! I liked the wrapper-style explanation of ChillDKG. It effectively separated the cryptographic details, making the document more approachable. However, it did take me several readings to fully understand certain concepts.

I didn’t find any significant issues, just a few suggestions to improve the clarity of this document. I will leave my suggestions in this issue and continue to add more as I come across them in future reviews.

## `README.md`

- In [SimplPedPop section](https://github.com/BlockstreamResearch/bip-frost-dkg/blob/master/README.md#dkg-protocol-simplpedpop)
    
    > Individual participants' public keys are added to the output of the DKG. This allows partial signature verification.
    > 
    
    public keys → public shares
    
- In [EncPedPop section](https://github.com/BlockstreamResearch/bip-frost-dkg/blob/master/README.md#dkg-protocol-encpedpop)
    - It would be helpful to mention [`self_pad`](https://github.com/BlockstreamResearch/bip-frost-dkg/blob/master/python/chilldkg_ref/encpedpop.py#L36) in this section
    
    > Participant `i` will additionally transmit their public encryption nonce and an encrypted VSS share `shares[j] + pad_ij` for every other participant `j` as part of the first message to the coordinator.
    > 
    
    > `secshare = enc_secshare - (pad_0j + ... + pad_nj)`
    > 
    - When reading the above lines, it wasn’t clear what the value of `pad_ii` should be—whether it should be 0 or something else.
- In [ChillDKG section](https://github.com/BlockstreamResearch/bip-frost-dkg/blob/master/README.md#dkg-protocol-chilldkg)
    
    > ChillDKG repurposes the host key pairs as the ECDH key pairs required by EncPedPop, and it repurposes the host secret key as the seed required by EncPedPop.
    > 
    - At the end of the sentence, EncPedPop → SimplPedPop

## Python Specification

- `./example.py` → `python3 example.py`

https://github.com/BlockstreamResearch/bip-frost-dkg/blob/54ea681cc1dc965845d4f06a9a3e1a0a27f8558e/all.sh#L9

- In `tests.sh`, Implement a function to check for Python version ≥ 3.10?
    - AFAIU, we need a higher version of Python because the code uses `zip(..., .., *strict*=True)`, which was introduced in [Python 3.10](https://realpython.com/python310-new-features/#stricter-zipping-of-sequences)
    - The BIP mentions that the spec is written in Python 3.12. Would it be helpful to include a Python version check?
    - We could add something like this in `tests.sh`
        ```bash
        check_python_version() {
            check_availability python3
            python3 -c 'import sys; sys.exit(sys.version_info < (3,10))' || {
                echo "Python 3.10 or higher is required." >&2
                exit 1
            }
        }
        ```
- When creating a PoP using `pop_prove`, the `schnorr_sign` function uses the tag `BIP DKG/pop message` for the challenge hash, but `BIP0340/aux` and `BIP0340/nonce` for nonce generation. Wouldn't it be more consistent to use `BIP DKG/` throughout `schnorr_sign`?
    - Should the `schnorr_sign` function be modified to take the `BIP_TAG` as an input argument instead of the entire `challenge_tag`?
- The functions in the `ecdh.py` file are missing return type annotations
- Should the `to_bytes` method in the `CoordinatorMsg` class be removed? It doesn't appear to be used anywhere, and the `ParticipantMsg` class doesn’t include a similar method.

https://github.com/BlockstreamResearch/bip-frost-dkg/blob/54ea681cc1dc965845d4f06a9a3e1a0a27f8558e/python/chilldkg_ref/simplpedpop.py#L66

- The README should be updated once the variant is finalized. Currently, it suggests to use `ecdh_uncompressed_in_raw_out`

https://github.com/BlockstreamResearch/bip-frost-dkg/blob/54ea681cc1dc965845d4f06a9a3e1a0a27f8558e/python/chilldkg_ref/encpedpop.py#L25-L26

- The `hash_sha256` function is not used anywhere.

https://github.com/BlockstreamResearch/bip-frost-dkg/blob/0964bd733c3e5f037615c1577b40b2aa03f6ed71/python/secp256k1proto/util.py#L23-L24

- nit: The method is defined as `invalid_taproot_commitment`, not `add_invalid_taproot_commitment`.

https://github.com/BlockstreamResearch/bip-frost-dkg/blob/121b946cfe095f0243efaee1a238c2c4fa1e1f7c/python/chilldkg_ref/vss.py#L83

**Comment by jonasnick** [comment]
Thanks @siv2r. I'll open a PR to address your comments

> At the end of the sentence, EncPedPop → SimplPedPop

I think using "EncPedPop" is actually intended here, because ChillDKG never calls SimplPedPop and EncPedPop als requires a seed.

> ./example.py → python3 example.py

Why? `example.py` has the correct shebang.

> Why is the coordinator being blamed here?

Because if the coordinator acts honestly (and messages are delivered honestly) then this can never happen. This is because both the participants pubshare and the partial pubshares are all computed from the same list of participant messages.

**Comment by siv2r** [comment]
> Why? `example.py` has the correct shebang.  

Ah, you're right—I didn’t notice the shebang. I saw `test.sh` using `python3 tests.py` and assumed `./example` might be a typo.

> This is because both the participants' pubshare and the partial pubshares are computed from the same list of participant messages.  

Got it, thanks! I misunderstood this check.

The scenario I referred to in  
> Couldn’t a malicious (unknown) participant have provided an invalid share (intended for the blaming participant) to the coordinator? Wouldn’t `UnknownFaultyParticipantOrCoordinatorError` be more appropriate here?  

would actually be caught by the `SecretshareSumError` check.

**Comment by jonasnick** [comment]
I address your comments in PR #67. Thanks again!

> In tests.sh, Implement a function to check for Python version ≥ 3.10?

I think it's better to just support all non-EOL python 3 versions.

> Should the schnorr_sign function be modified to take the BIP_TAG as an input argument instead of the entire challenge_tag?

Yes. Great catch. The API right now is extremely dangerous. If you sign twice with the same secret key and different challenge tag you will reuse your nonce.

> Should the to_bytes method in the CoordinatorMsg class be removed? It doesn't appear to be used anywhere, and the ParticipantMsg class doesn’t include a similar method.

Instead of removing it, we need to add `to_bytes()` methods to all `*Msg` classes.

> The hash_sha256 function is not used anywhere.

Yeah, it's supposed to become a standalone library. Maybe worth keeping for that reason.
